### ISSUE TITLE
Use libhand API in a new project

### ISSUE THREAD

**Issue by AristoYU** [libhand/libhand#14]
I have created a new project and I want to use your API. 

I have created a path `cmake/Module` in that project and I have copied 

`FindLibHand.cmake`,

`LibHandConfig.cmake`,

`LibHand-export.cmake`,

`LibHand-export-noconfig.cmake` 

into that folder. In `CmakeLists.txt`, I have written `find_package(LibHand REQUIRED)` and I have set `CMAKE_MODULE_PATH` to that path. But when I run `make` in the terminal, it shows me
```
make[3]: *** No rule to make target 'hand_hog-NOTFOUND', needed by 'main.bin'.  Stop.
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/main.bin.dir/all' failed
make[2]: *** [CMakeFiles/main.bin.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/main.bin.dir/rule' failed
make[1]: *** [CMakeFiles/main.bin.dir/rule] Error 2
Makefile:118: recipe for target 'main.bin' failed
make: *** [main.bin] Error 2
```

What can I do? 

Thanks

**Comment by shasheene** [comment]
There a more CMake-y way of doing this, I believe using the find_packages thing to set the paths, but here's a [method that I used a few years ago](https://github.com/shasheene/gloveTrack/blob/master/CMakeLists.txt) which sets the paths to libhand relative to the base directory of the project.
```
cmake_minimum_required (VERSION 2.8)
project (YOUR_PROJECT)

# ExternalProject module allows triggering of build AND install targets (required for eg, some third-party libs)
include(ExternalProject)

# We assume the libhand repository is in a sibling directory to YOUR_PROJECT source C++ code
SET(HAND_LIB_ROOT_DIR "${CMAKE_SOURCE_DIR}/third-party/libhand")

SET(HAND_LIB_DIST_DIR "${HAND_LIB_ROOT_DIR}/dist")
SET(HAND_LIB_EXAMPLES_DIR "${HAND_LIB_ROOT_DIR}/examples")
SET(HAND_LIB_API_DIR "${HAND_LIB_ROOT_DIR}/hand_cpp/source/")

# Add YOUR_PROJECT source
ADD_SUBDIRECTORY("${CMAKE_SOURCE_DIR}/src")
````


```
# Build LibHand (see https://github.com/libhand/libhand for detailed installation instructions) 
cd third-party/libhand/ && mkdir build && cd build/
cmake ..
make
# Collate libhand build artifacts in *local* directory
make install

# Build YOUR_PROJECT
cd ../../../
mkdir build
cd build

cmake ..
make
```

I haven't looked at libhand for a few years. I do eventually want to improve a lot of things. Happy to accept pull requests with a better approach.

Please reply if you have success and I'll close the issue.

**Comment by AristoYU** [comment]
Well, sorry to bother you. It worked after restarting system.

Thank you for your reply.
